# Generated by Django 4.1.4 on 2023-01-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('op1', models.TextField(max_length=200)),
                ('op2', models.TextField(max_length=200)),
                ('op3', models.TextField(max_length=200)),
                ('op4', models.TextField(max_length=200)),
                ('ans', models.TextField(max_length=200)),
            ],
        ),
    ]
