# Generated by Django 4.1.4 on 2023-01-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='ans',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='op1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='op2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='op3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='op4',
            field=models.TextField(),
        ),
    ]
