# Generated by Django 4.2.11 on 2024-03-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_adress',
        ),
    ]
