# Generated by Django 4.2.11 on 2024-05-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0005_option_question_delete_questionmodel_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Quizapp.question'),
        ),
    ]
